version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn test -Dspring.profiles.active=test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package -Dspring.profiles.active=test
artifacts:
  files:
    - target/checkregister.jar
    - appspec.yml
  discard-paths: yes
