

spring:
  redis:
    port: 6379
    host: localhost

  jpa:
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/checkregister
    username: root
    password: fossil

    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      validation-query: SELECT 1
      max-total: 1




