

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/checkregister
    username: user
    password: pass

    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
      test-on-borrow: true
      validation-query: SELECT 1
      max-total: 1

  jpa:
    show-sql: true
